### ISSUE TITLE
can't find the code for ChatGPT augmentation

### ISSUE THREAD

**Issue by vhd2023** [yhydhx/AugGPT#1]
Greetings! I am writing to express my keen interest in your work, also I can't find the code and prompts  for generating augmentation using ChatGPT, could you name the related files please? I would greatly appreciate your guidance. Thank you for your immense contributions to the community.

Best regards

**Comment by 1SingleFeng** [comment]
> Greetings! I am writing to express my keen interest in your work, also I can't find the code and prompts for generating augmentation using ChatGPT, could you name the related files please? I would greatly appreciate your guidance. Thank you for your immense contributions to the community.
> 
> Best regards

我也有这个需求，请问你找到了吗

**Comment by evantian110** [comment]
> > Greetings! I am writing to express my keen interest in your work, also I can't find the code and prompts for generating augmentation using ChatGPT, could you name the related files please? I would greatly appreciate your guidance. Thank you for your immense contributions to the community.
> > Best regards
> 
> 我也有这个需求，请问你找到了吗

请问你知道transrate的实现方式吗

**Comment by kingofacewang** [comment]
> Greetings! I am writing to express my keen interest in your work, also I can't find the code and prompts for generating augmentation using ChatGPT, could you name the related files please? I would greatly appreciate your guidance. Thank you for your immense contributions to the community.问候！我写信是为了表达我对你的工作的浓厚兴趣，而且我找不到使用 ChatGPT 生成增强的代码和提示，你能命名相关文件吗？我将非常感谢您的指导。感谢您对社区的巨大贡献。
> 
> Best regards 此致

I also have this need, can you find it?

**Comment by yhydhx** [comment]
For augmentation data generation. You can simply using the prompt shown in the article to generate few more samples. And placed the augmented data into the data folder.  If you want to generate more samples, you can leverage the API of any Large Language Model.

**Comment by yhydhx** [comment]
Then follow the structure showed in the data folder and run the commend in the README, then you can get the new metric result with the augmented data.
